// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-doctors.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.84.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const key = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY",
    "SUPABASE_ANON_KEY",
    "VITE_SUPABASE_ANON_KEY"
  ]);
  if (!key) {
    throw new Error("SUPABASE_PUBLISHABLE_KEY (or SUPABASE_ANON_KEY) is required");
  }
  return key;
}
function supabaseForUser(ctx) {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-doctors.ts
var list_doctors_default = defineTool({
  name: "list_doctors",
  title: "List doctors",
  description: "List clinician profiles in the clinic roster, optionally only active ones.",
  inputSchema: {
    active_only: z.boolean().optional().describe("Only return active doctors. Defaults to true.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ active_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("doctor_profiles").select("id,name,title,specialization,languages,years_of_experience,is_active").order("name");
    if (active_only !== false) query = query.eq("is_active", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { doctors: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-appointments.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_appointments_default = defineTool2({
  name: "list_appointments",
  title: "List appointments",
  description: "List clinic appointments, optionally filtered by date (YYYY-MM-DD), status, or doctor id.",
  inputSchema: {
    date: z2.string().optional().describe("Appointment date in YYYY-MM-DD format."),
    status: z2.string().optional().describe("Appointment status, e.g. scheduled or cancelled."),
    doctor_id: z2.string().optional().describe("Doctor profile id to filter by."),
    limit: z2.number().int().optional().describe("Maximum rows to return (default 50, max 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date, status, doctor_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("appointments").select(
      "id,appointment_date,appointment_time,duration_minutes,status,doctor_id,patient_name,patient_phone,notes"
    ).order("appointment_date").order("appointment_time").limit(Math.min(Math.max(limit ?? 50, 1), 200));
    if (date) query = query.eq("appointment_date", date);
    if (status) query = query.eq("status", status);
    if (doctor_id) query = query.eq("doctor_id", doctor_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { appointments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-appointment.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.25.76";
var create_appointment_default = defineTool3({
  name: "create_appointment",
  title: "Create appointment",
  description: "Book a new clinic appointment for a patient.",
  inputSchema: {
    patient_name: z3.string().trim().min(1).describe("Patient name."),
    patient_phone: z3.string().trim().min(1).describe("Patient mobile number."),
    appointment_date: z3.string().describe("Date in YYYY-MM-DD format."),
    appointment_time: z3.string().describe("Time in HH:MM (24h) format."),
    doctor_id: z3.string().optional().describe("Doctor profile id."),
    duration_minutes: z3.number().int().optional().describe("Duration in minutes (default 30)."),
    notes: z3.string().optional().describe("Operational notes for the visit.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("appointments").insert({
      patient_name: input.patient_name,
      patient_phone: input.patient_phone,
      appointment_date: input.appointment_date,
      appointment_time: input.appointment_time,
      doctor_id: input.doctor_id ?? null,
      duration_minutes: input.duration_minutes ?? 30,
      notes: input.notes ?? null
    }).select();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0]) }],
      structuredContent: { appointment: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/tools/list-doctor-shifts.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_doctor_shifts_default = defineTool4({
  name: "list_doctor_shifts",
  title: "List doctor shifts",
  description: "List the clinic's recurring doctor shifts, optionally for one day of the week.",
  inputSchema: {
    day_of_week: z4.string().optional().describe("Day of week, e.g. Monday.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ day_of_week }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("doctor_shifts").select("id,day_of_week,start_time,end_time,service_type,doctor_shift_assignments(doctor_id)").order("start_time");
    if (day_of_week) query = query.eq("day_of_week", day_of_week);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { shifts: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cagjnhbjkqubqmbvypaq";
var mcp_default = defineMcp({
  name: "clinicq-staff-dashboard",
  title: "ClinicQ Staff Dashboard",
  version: "0.1.0",
  instructions: "Tools for the ClinicQ staff dashboard. Read the doctor roster and shift schedule, list clinic appointments, and book new appointments. All calls act as the signed-in clinic staff user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_doctors_default, list_doctor_shifts_default, list_appointments_default, create_appointment_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
